Repository kahluaband/Homepage_BE_SpringBoot, pull requests merged in 2024-11, with the labels that each got.

#75 #74 Feat: add post, comment, postimage domain
  src/main/java/kahlua/KahluaProject/apipayload/code/status/ErrorStatus.java
  src/main/java/kahlua/KahluaProject/controller/PostController.java
  src/main/java/kahlua/KahluaProject/converter/PostConverter.java
  src/main/java/kahlua/KahluaProject/domain/post/Comment.java
  src/main/java/kahlua/KahluaProject/domain/post/Post.java
  src/main/java/kahlua/KahluaProject/domain/post/PostImage.java
  src/main/java/kahlua/KahluaProject/dto/post/request/CommentsCreateRequest.java
  src/main/java/kahlua/KahluaProject/dto/post/request/PostCreateRequest.java
  src/main/java/kahlua/KahluaProject/dto/post/request/PostImageCreateRequest.java
  src/main/java/kahlua/KahluaProject/dto/post/response/PostCreateResponse.java
  src/main/java/kahlua/KahluaProject/dto/post/response/PostImageCreateResponse.java
  src/main/java/kahlua/KahluaProject/repository/PostImageRepository.java
  src/main/java/kahlua/KahluaProject/repository/PostRepository.java
  src/main/java/kahlua/KahluaProject/service/PostService.java
Labels: ✨ Feature

#85 Feat: 웹 소켓 이벤트 리스너, STOMP 핸들러 구현
  build.gradle
  src/main/java/kahlua/KahluaProject/apipayload/code/status/ErrorStatus.java
  src/main/java/kahlua/KahluaProject/config/WebSocketConfig.java
  src/main/java/kahlua/KahluaProject/dto/reservation/request/SubRequest.java
  src/main/java/kahlua/KahluaProject/security/jwt/JwtProvider.java
  src/main/java/kahlua/KahluaProject/websocket/StompHandler.java
  src/main/java/kahlua/KahluaProject/websocket/WebSocketEventListener.java
  src/main/java/kahlua/KahluaProject/websocket/WebSocketException.java
Labels: ✨ Feature

#88 #69 Fix: 인증로직 수정사항 반영
  src/main/java/kahlua/KahluaProject/websocket/StompHandler.java
Labels: 🎀 Fix

#90 #74 Feat: create likes and viewing post functions
  src/main/java/kahlua/KahluaProject/apipayload/code/status/ErrorStatus.java
  src/main/java/kahlua/KahluaProject/controller/PostController.java
  src/main/java/kahlua/KahluaProject/converter/PostConverter.java
  src/main/java/kahlua/KahluaProject/domain/post/Post.java
  src/main/java/kahlua/KahluaProject/domain/post/PostLikes.java
  src/main/java/kahlua/KahluaProject/dto/post/request/PostCreateRequest.java
  src/main/java/kahlua/KahluaProject/dto/post/response/PostGetResponse.java
  src/main/java/kahlua/KahluaProject/dto/post/response/PostImageGetResponse.java
  src/main/java/kahlua/KahluaProject/repository/post/PostLikesRepository.java
  src/main/java/kahlua/KahluaProject/repository/post/PostRepository.java
  src/main/java/kahlua/KahluaProject/service/PostService.java
Labels: ✨ Feature

#89 Feat: 동방 예약 기능 구현
  src/main/java/kahlua/KahluaProject/apipayload/code/status/ErrorStatus.java
  src/main/java/kahlua/KahluaProject/config/SecurityConfig.java
  src/main/java/kahlua/KahluaProject/controller/ReservationController.java
  src/main/java/kahlua/KahluaProject/converter/ReservationConverter.java
  src/main/java/kahlua/KahluaProject/domain/reservation/ReservationStatus.java
  src/main/java/kahlua/KahluaProject/dto/reservation/request/ReservationProceedRequest.java
  src/main/java/kahlua/KahluaProject/dto/reservation/request/ReservationRequest.java
  src/main/java/kahlua/KahluaProject/dto/reservation/response/ReservationListResponse.java
  src/main/java/kahlua/KahluaProject/dto/reservation/response/ReservationResponse.java
  src/main/java/kahlua/KahluaProject/repository/reservation/ReservationCustomRepository.java
  src/main/java/kahlua/KahluaProject/repository/reservation/ReservationCustomRepositoryImpl.java
  src/main/java/kahlua/KahluaProject/repository/reservation/ReservationRepository.java
  src/main/java/kahlua/KahluaProject/service/ReservationService.java
Labels: ✨ Feature

#91 Feat: 공연 예매/지원자 통계 조회 API
  src/main/java/kahlua/KahluaProject/config/SecurityConfig.java
  src/main/java/kahlua/KahluaProject/controller/adminController/AdminApplyController.java
  src/main/java/kahlua/KahluaProject/controller/adminController/AdminTicketController.java
  src/main/java/kahlua/KahluaProject/dto/apply/response/ApplyStatisticsResponse.java
  src/main/java/kahlua/KahluaProject/dto/ticket/response/TicketStatisticsResponse.java
  src/main/java/kahlua/KahluaProject/repository/ApplyRepository.java
  src/main/java/kahlua/KahluaProject/repository/ticket/TicketRepository.java
  src/main/java/kahlua/KahluaProject/service/ApplyService.java
  src/main/java/kahlua/KahluaProject/service/TicketService.java
Labels: ✨ Feature

#94 Feat: 게시판 오프셋 페이지네이션
  src/main/java/kahlua/KahluaProject/controller/PostController.java
  src/main/java/kahlua/KahluaProject/converter/PostConverter.java
  src/main/java/kahlua/KahluaProject/domain/post/Post.java
  src/main/java/kahlua/KahluaProject/domain/post/PostType.java
  src/main/java/kahlua/KahluaProject/repository/post/PostRepository.java
  src/main/java/kahlua/KahluaProject/repository/post/PostRepositoryCustom.java
  src/main/java/kahlua/KahluaProject/repository/post/PostRepositoryImpl.java
  src/main/java/kahlua/KahluaProject/service/PostService.java
Labels: ✨ Feature

#97 #74 Feat: add postType in post service
  src/main/java/kahlua/KahluaProject/converter/PostConverter.java
  src/main/java/kahlua/KahluaProject/dto/post/request/PostCreateRequest.java
  src/main/java/kahlua/KahluaProject/dto/post/response/PostCreateResponse.java
  src/main/java/kahlua/KahluaProject/service/PostService.java
Labels: ✨ Feature

#99 #69 Refactor: 마이페이지 컨트롤러 생성
  src/main/java/kahlua/KahluaProject/controller/MyPageController.java
  src/main/java/kahlua/KahluaProject/controller/ReservationController.java
Labels: 🔨 Refactor
