Repository kahluaband/Homepage_BE_SpringBoot, pull requests merged in 2024-07, with the labels that each got.

#14 Fix: BaseEntity 수정
  src/main/java/kahlua/KahluaProject/domain/BaseEntity.java
Labels: 🎀 Fix

#13 #9 Feat : add status column in ticket domain
  src/main/java/kahlua/KahluaProject/domain/ticket/Status.java
  src/main/java/kahlua/KahluaProject/domain/ticket/Ticket.java
Labels: ✨ Feature

#20 #17 Feat: make admin-apply list & detail function
  src/main/java/kahlua/KahluaProject/controller/AdminController.java
  src/main/java/kahlua/KahluaProject/dto/response/ApplyItemResponse.java
  src/main/java/kahlua/KahluaProject/dto/response/ApplyListResponse.java
  src/main/java/kahlua/KahluaProject/service/ApplyService.java
Labels: ✨ Feature

#19 #9 Feat: make ticket function (demo)
  src/main/java/kahlua/KahluaProject/controller/TicketController.java
  src/main/java/kahlua/KahluaProject/converter/TicketConverter.java
  src/main/java/kahlua/KahluaProject/domain/ticket/Participants.java
  src/main/java/kahlua/KahluaProject/domain/ticket/Ticket.java
  src/main/java/kahlua/KahluaProject/dto/request/ParticipantsCreateRequest.java
  src/main/java/kahlua/KahluaProject/dto/request/TicketCreateRequest.java
  src/main/java/kahlua/KahluaProject/dto/response/ParticipantsResponse.java
  src/main/java/kahlua/KahluaProject/dto/response/TicketCreateResponse.java
  src/main/java/kahlua/KahluaProject/dto/response/TicketGetResponse.java
  src/main/java/kahlua/KahluaProject/repository/ParticipantsRepository.java
  src/main/java/kahlua/KahluaProject/repository/TicketRepository.java
  src/main/java/kahlua/KahluaProject/service/TicketService.java
Labels: ✨ Feature

#22 Feat: 어드민 페이지 로그인 개발
  build.gradle
  src/main/java/kahlua/KahluaProject/apipayload/ExceptionResponse.java
  src/main/java/kahlua/KahluaProject/apipayload/code/status/ErrorStatus.java
  src/main/java/kahlua/KahluaProject/confg/RedisConfig.java
  src/main/java/kahlua/KahluaProject/confg/SecurityConfig.java
  src/main/java/kahlua/KahluaProject/confg/SwaggerConfig.java
  src/main/java/kahlua/KahluaProject/controller/AuthController.java
  src/main/java/kahlua/KahluaProject/controller/UserController.java
  src/main/java/kahlua/KahluaProject/converter/AuthConverter.java
  src/main/java/kahlua/KahluaProject/converter/UserConverter.java
  src/main/java/kahlua/KahluaProject/domain/BaseEntity.java
  src/main/java/kahlua/KahluaProject/domain/user/Credential.java
  src/main/java/kahlua/KahluaProject/domain/user/User.java
  src/main/java/kahlua/KahluaProject/domain/user/UserType.java
  src/main/java/kahlua/KahluaProject/dto/request/SignInRequest.java
  src/main/java/kahlua/KahluaProject/dto/request/SignUpRequest.java
  src/main/java/kahlua/KahluaProject/dto/response/SignInResponse.java
  src/main/java/kahlua/KahluaProject/dto/response/TokenResponse.java
  src/main/java/kahlua/KahluaProject/dto/response/UserResponse.java
  src/main/java/kahlua/KahluaProject/redis/RedisClient.java
  src/main/java/kahlua/KahluaProject/repository/CredentialRepository.java
  src/main/java/kahlua/KahluaProject/repository/UserRepository.java
  src/main/java/kahlua/KahluaProject/security/AuthDetails.java
  src/main/java/kahlua/KahluaProject/security/AuthDetailsService.java
  src/main/java/kahlua/KahluaProject/security/ExceptionFilter.java
  src/main/java/kahlua/KahluaProject/security/jwt/JwtAccessDeniedHandler.java
  src/main/java/kahlua/KahluaProject/security/jwt/JwtAuthenticationHandler.java
  src/main/java/kahlua/KahluaProject/security/jwt/JwtFilter.java
  src/main/java/kahlua/KahluaProject/security/jwt/JwtProvider.java
  src/main/java/kahlua/KahluaProject/service/AuthService.java
  src/main/java/kahlua/KahluaProject/service/CredentialService.java
  src/main/java/kahlua/KahluaProject/service/UserService.java
Labels: 📬 API, ✨ Feature

#28 #16 Fix: authorize 경로 수정
  src/main/java/kahlua/KahluaProject/confg/SecurityConfig.java
Labels: 🎀 Fix

#37 #17 Feat: make admin-apply count & sort by preference
  src/main/java/kahlua/KahluaProject/controller/AdminController.java
  src/main/java/kahlua/KahluaProject/converter/ApplyConverter.java
  src/main/java/kahlua/KahluaProject/domain/apply/Apply.java
  src/main/java/kahlua/KahluaProject/dto/apply/response/ApplyItemResponse.java
  src/main/java/kahlua/KahluaProject/dto/apply/response/ApplyListResponse.java
  src/main/java/kahlua/KahluaProject/repository/ApplyRepository.java
  src/main/java/kahlua/KahluaProject/service/ApplyService.java
Labels: ✨ Feature, 🎀 Fix

#42 #1 Refactor apply api
  src/main/java/kahlua/KahluaProject/apipayload/code/status/ErrorStatus.java
  src/main/java/kahlua/KahluaProject/controller/ApplyController.java
  src/main/java/kahlua/KahluaProject/converter/ApplyConverter.java
  src/main/java/kahlua/KahluaProject/domain/apply/Apply.java
  src/main/java/kahlua/KahluaProject/repository/ApplyRepository.java
  src/main/java/kahlua/KahluaProject/service/ApplyService.java
Labels: 🔨 Refactor

#43 Admin ticket
  src/main/java/kahlua/KahluaProject/apipayload/code/status/ErrorStatus.java
  src/main/java/kahlua/KahluaProject/controller/AdminController.java
  src/main/java/kahlua/KahluaProject/controller/adminController/AdminApplyController.java
  src/main/java/kahlua/KahluaProject/controller/adminController/AdminTicketController.java
  src/main/java/kahlua/KahluaProject/repository/TicketRepository.java
  src/main/java/kahlua/KahluaProject/service/TicketService.java
Labels: ✨ Feature

#45 #9 Fix: modify method to update deleted_at field
  src/main/java/kahlua/KahluaProject/domain/BaseEntity.java
  src/main/java/kahlua/KahluaProject/domain/ticket/Ticket.java
  src/main/java/kahlua/KahluaProject/domain/user/Credential.java
  src/main/java/kahlua/KahluaProject/domain/user/User.java
  src/main/java/kahlua/KahluaProject/service/TicketService.java
Labels: 🎀 Fix
