Repository kahluaband/Homepage_BE_SpringBoot, pull requests merged in 2024-08, with the labels that each got.

#46 #21 Fix: add studentId response in freshman admin list
  src/main/java/kahlua/KahluaProject/dto/ticket/response/TicketItemResponse.java
  src/main/java/kahlua/KahluaProject/service/TicketService.java
Labels: 🎀 Fix

#41 #40 Test: make ticket test code
  src/main/java/kahlua/KahluaProject/domain/ticket/Ticket.java
  src/test/java/kahlua/KahluaProject/domain/ticket/TicketUtilTest.java
  src/test/java/kahlua/KahluaProject/domain/ticket/ticketDomainTest.java
Labels: ✅ Test

#51 #3 Feat: add forward header filter
  src/main/java/kahlua/KahluaProject/config/WebConfig.java
Labels: ⚙ Setting

#57 #3 Fix: resolve jpa redis repository scan
  src/main/java/kahlua/KahluaProject/DemoApplication.java
Labels: ⚙ Setting, 🎀 Fix

#58 #3 Fix: fix DemoApplication jpa repository annotation
  src/main/java/kahlua/KahluaProject/DemoApplication.java
Labels: ⚙ Setting, 🎀 Fix

#59 Chore: 임시 프론트 주소 추가
  src/main/java/kahlua/KahluaProject/config/CorsMvcConfig.java
  src/main/java/kahlua/KahluaProject/config/SecurityConfig.java
Labels: 🛠️ Chore
