Repository kahluaband/Homepage_BE_SpringBoot, pull requests merged in 2025-02, with the labels that each got.

#140 Feature: 공연리스트 api, 공연 상세정보 조회 api 구현
  src/main/java/kahlua/KahluaProject/apipayload/code/status/ErrorStatus.java
  src/main/java/kahlua/KahluaProject/controller/PerformanceController.java
  src/main/java/kahlua/KahluaProject/converter/TicketConverter.java
  src/main/java/kahlua/KahluaProject/converter/TicketInfoConverter.java
  src/main/java/kahlua/KahluaProject/domain/ticketInfo/PerformanceStatus.java
  src/main/java/kahlua/KahluaProject/domain/ticketInfo/TicketInfo.java
  src/main/java/kahlua/KahluaProject/dto/ticketInfo/response/PerformanceRes.java
  src/main/java/kahlua/KahluaProject/dto/ticketInfo/response/TicketInfoResponse.java
  src/main/java/kahlua/KahluaProject/repository/ticket/TicketInfoRepository.java
  src/main/java/kahlua/KahluaProject/service/PerformanceService.java
  src/main/java/kahlua/KahluaProject/vo/TicketInfoData.java
Labels: ✨ Feature

#141 Feature: 공연생성 api 구현
  build.gradle
  src/main/java/kahlua/KahluaProject/controller/PerformanceController.java
  src/main/java/kahlua/KahluaProject/converter/TicketConverter.java
  src/main/java/kahlua/KahluaProject/converter/TicketInfoConverter.java
  src/main/java/kahlua/KahluaProject/domain/ticketInfo/TicketInfo.java
  src/main/java/kahlua/KahluaProject/dto/ticketInfo/request/TicketInfoRequest.java
  src/main/java/kahlua/KahluaProject/service/PerformanceService.java
  src/main/java/kahlua/KahluaProject/service/TicketService.java
Labels: ✨ Feature

#145 Refactor: 공연 리스트 api 수정
  src/main/java/kahlua/KahluaProject/controller/PerformanceController.java
  src/main/java/kahlua/KahluaProject/converter/TicketInfoConverter.java
  src/main/java/kahlua/KahluaProject/domain/ticketInfo/TicketInfo.java
  src/main/java/kahlua/KahluaProject/repository/ticket/TicketInfoRepository.java
  src/main/java/kahlua/KahluaProject/repository/ticket/TicketInfoRepository/TicketInfoCustomRepository.java
  src/main/java/kahlua/KahluaProject/repository/ticket/TicketInfoRepository/TicketInfoCustomRepositoryImpl.java
  src/main/java/kahlua/KahluaProject/repository/ticket/TicketInfoRepository/TicketInfoRepository.java
  src/main/java/kahlua/KahluaProject/repository/ticket/TicketRepository/TicketCustomRepository.java
  src/main/java/kahlua/KahluaProject/repository/ticket/TicketRepository/TicketCustomRepositoryImpl.java
  src/main/java/kahlua/KahluaProject/repository/ticket/TicketRepository/TicketRepository.java
  src/main/java/kahlua/KahluaProject/service/ExcelConvertService.java
  src/main/java/kahlua/KahluaProject/service/PerformanceService.java
  src/main/java/kahlua/KahluaProject/service/TicketService.java
Labels: 🔨 Refactor, 🎀 Fix

#148 fix: 공연날짜 최신순으로 변경 & 커서 에러 해결 (#147)
  src/main/java/kahlua/KahluaProject/repository/ticket/TicketInfoRepository/TicketInfoCustomRepository.java
  src/main/java/kahlua/KahluaProject/repository/ticket/TicketInfoRepository/TicketInfoCustomRepositoryImpl.java
  src/main/java/kahlua/KahluaProject/service/PerformanceService.java
Labels: 🎀 Fix
